name: .NET 6 CI with Tests and Push

on:
  push:  # Trigger the workflow on git push by any team member
    branches-ignore:
      - main
      - develop  # Exclude main and develop branches

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET 6
      - name: Set up .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the solution
      - name: Build solution
        run: dotnet build
        
      - name: Run Architectural Tests
        run: dotnet test /Tests/Monolith.Architecture.Tests/Architectural.Tests/Architectural.Tests.csproj --no-restore --verbosity normal
        continue-on-error: false  # Workflow fails if tests fail

      # Step 6: Push changes back to the branch if tests succeed
      - name: Push changes if tests pass
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git push origin HEAD
        if: success()  # Only push if tests pass
